### ISSUE TITLE
feature i2c fails to compile if feature spi isn't enabed

### ISSUE THREAD

**Issue by webhet** [cfrenette/bma400-rs#7]
Hi,
very cool and well designed crate.

Just noticed a problem when wanting to use the i2c feature only. This doesn't compile and gives the error:

```
error[E0432]: unresolved import `spi`
   --> /home/.../.cargo/registry/src/github.com-1ecc6299db9ec823/bma400-0.1.0/src/lib.rs:193:9
    |
193 | pub use spi::SPIInterface;
    |         ^^^ help: a similar path exists: `embedded_hal::spi`

```

I think [L193](https://github.com/cfrenette/bma400-rs/blob/main/src/lib.rs#L192) should use cfg(...spi...)  instead of i2c.

**Comment by cfrenette** [comment]
You are correct @webhet, good catch and thank you for reporting this! I've made the changes above. I'll merge them into a new release and publish to crates.io shortly.
